services:

  bruschetta:
    image: "bruschetta:${TAG-latest}"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app:cached
    tty: true
    restart: unless-stopped
