services:

  bruschetta-api-devel:
    image: "bruschetta-api:${TAG-devel}"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app:cached
    tty: true
    restart: unless-stopped
